---
# tasks file for nginx
# Description: Nginx Install and Config
- name: Include appropriate vars file
  include_vars: "{{ var_type }}.yml"

- name: Install Nginx and Certbot
  yum:
    name:
      - nginx
    state: latest
    
- name: Main Nginx Config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create available and enabled dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/etc/nginx/conf.d/available"
    - "/etc/nginx/conf.d/enabled"

- name: Available Site Configs
  template:
    src: "{{ item }}-rpoxy.conf.j2"
    dest: "/etc/nginx/conf.d/available/{{ item }}-rproxy.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items: "{{ web_server }}"

- name: Enabled Site Links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: root
    group: root
    force: yes
  with_items:
    - src: "/etc/nginx/conf.d/available/{{ web_server }}-rproxy.conf"
      dest: "/etc/nginx/conf.d/enabled/{{ web_server }}.conf"
  
- name: Create Jenkins logging dir
  file:
    path: "/var/log/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ web_server }}"

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
