---
# tasks file for ec2-instance

- name: create a new developer ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}" # security group name
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: true
    instance_profile_name: "{{ iam }}"
    region: "{{ region }}"
    count: 1 #default
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ vol_size }}"
        delte_on_termination: yes
        tags:
          - Project: "{{ proj_tag }}"
    count_tag:
      Name: "{{ name_tag }}"
      Project: "{{ proj_tag }}"
    instance_tags:
      Name: "{{ name_tag }}"
      Project: "{{ proj_tag }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
  register: ec2_provision_result

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2_provision_result.instances }}"

- name: Create SSH Group to login dynamically to EC2 Instance
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: ec2_server
  with_items: "{{ ec2_provision_result.instances }}"

