- name: Create a new EC2 developer Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-west-2
    instance_type: "{{ inst_type | default('t2.micro') }}"
    username: "{{ user | default('epost') }}"
    keypair: "{{ key | default('epostsquids') }}"
    name_tag: "SquidsDevelopment"
    ec2build: true
  tasks:
  - name: Add override host
    when: override_host is defined
    add_host:
      hostname: "{{ override_host }}"
      groups: ec2_server
    changed_when: false

  roles:
    - { role: 'ec2-create', when: ec2build }

- name: Configure instance
  hosts: ec2_server
  remote_user: ec2-user
  become: True
  gather_facts: True
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    efsmount: true

  roles:
    - development-instance
    - { role: 'efs-mount', when: efsmount}

  tasks:
  - include_vars: users.yml

  - name: Crate /users directory
    file:
      path: /users
      state: directory

  - name: Add users | create users, shell, home dirs
    user:
      name: '{{ item.username }}'
      shell: /bin/bash
      uid: '{{ item.uid }}'
      createhome: yes
      home: "/users/{{ item.username }}"
      comment: 'create with anisble'
      append: yes
    with_items: '{{ users }}'

  - name: Setup | authorized key upload
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
    with_items: '{{ users }}'

  - name: sudoers | update sudoers file and validate
    lineinfile:
      path: /etc/sudoers
      insertafter: EOF
      line: '{{ item.username }} ALL =(ALL) NOPASSWD: ALL'
      regexp: '^{{ item.username }} .*'
      state: present
    when: item.use_sudo
    with_items: '{{ users }}'
