---
# tasks file for ddclient
- name: Include appropriate vars file
  include_vars: "{{ var_type }}.yml"

- name: Install ddclient
  yum:
    lock_timeout: 180
    name: ddclient
    state: present

- name: Configure ddclient
  template:
    src: ddclient.conf.j2
    dest: "{{ ddclient_conf_path }}"

- name: Start and enable ddclient
  service:
    name: ddclient
    state: started
    enabled: true
