---
# tasks file for development-instance
- name: Update all packages to latest
  yum:
    lock_timeout: 180
    name: '*'
    state: latest

- name: Install development tools
  yum:
    lock_timeout: 180
    state: present
    update_cache: true
    name:
      - cscope
      - git
      - amazon-efs-utils
      - tmux
      - ansible
      - python-boto3
      - python2-boto
      - emacs

- name: Enable service nfs and ensure it is not masked
  systemd:
    name: nfs
    enabled: true
    state: started
    masked: false

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
