---
# tasks file for jenkin-docker-worker
- name:  Add the epel repo
  yum:
    lock_timeout: 180
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
    state: present

- name:  Add the IUS repo
  yum:
    lock_timeout: 180
    name: 'https://centos7.iuscommunity.org/ius-release.rpm'
    state: present

- name: Update all packages to latest
  yum:
    lock_timeout: 180
    name: '*'
    state: latest
  
- name: Install Worker Software
  yum:
    lock_timeout: 180
    state: present
    name:
      - ansible
      - awscli
      - git2u
      - git-lfs
      - java-1.8.0-openjdk
      - python2-boto

- name: Add the user 'jenkins' with a specific uid and a primary group of 'wheel'
  user:
    name: jenkins
    comment: Jenkins Slave
    uid: 6000
    groups: wheel
    shell: /bin/zsh
    home: /jenkins
    create_home: true
