---
# defaults file for jenkins-install
jenkins_home: /var/lib/jenkins
jenkins_http_port: 8080
jenkins_http_port_param: 8080
jenkins_init_file: /etc/sysconfig/jenkins
jenkins_java_options_env_var: JENKINS_JAVA_OPTIONS
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_jar_location: /opt/jenkins-cli.
jenkins_url_prefix: ""

jenkins_user: jenkins
jenkins_group: "{{ jenkins_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
