---
# tasks file for jenkins-install

- name: Ensure Java is installed
  package:
    name:
      - java-1.8.0-openjdk
    state: present

- name: Define Jenkins Repo
  set_fact:
    jenkins_repo: "{{ jenkins_repo }}"
    jenkins_key: "{{ jenkins_repo_key }}"
    jenkins_pkg: "{{ jenkins_pkg }}"
    jenkins_version: "{{ jenkins_version }}"

- name: Ensure dependecies are installed
  package:
    name:
      - curl
      - libselinux-python
      - initscripts
    state: present

- name: Ensure Jenkins repo is installed
  get_url:
    url: "{{ jenkins_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key }}"

- name: Download specific Jenkins version
  get_url:
    url: "{{ jenkins_pkg }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins-{{ jenkins-version }}-1.1.noarch.rpm"

- name: Install our specific version of Jenkins
  package:
    name: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    state: present
  notify: configure default users
